spring:
  datasource:
    url: jdbc:h2:mem:digitalwallet
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

wallet:
  withdraw:
    min-amount: 5
    max-amount: 5000
  send:
    min-amount: 10
    max-amount: 10000
  default-currency: GBP